export * from './Footer.styles';
export * from './Header.styles';
export * from './Main.styles';
export * from './Section.styles';
export * from './Logo.styles';
export * from './SimilarMovies.styles';
export * from './LatestMovie.style';
export * from './Table.styles';
export * from './TrendingCards.styles';
